name: SecurityMonkey
description: An AWS Policy Monitoring Tool
dependencies:
  angular: '0.12.0'
  browser: '0.10.0+2'
  http_server: '0.9.2+2'
dev_dependencies:
  unittest: '0.11.0+2'
transformers:
- angular
- $dart2js:
    minify: true
